# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raylet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import volpy_pb2 as volpy__pb2

from .volpy_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0craylet.proto\x12\x06raylet\x1a\x0bvolpy.proto\"\x1a\n\nWorkerData\x12\x0c\n\x04port\x18\x01 \x01(\t2\xc4\x01\n\x05Volpy\x12+\n\nInitWorker\x12\x12.raylet.WorkerData\x1a\x07.Status\"\x00\x12)\n\nCreateTask\x12\x10.TaskNameAndCode\x1a\x07.Status\"\x00\x12%\n\nSubmitTask\x12\x0b.IdTaskArgs\x1a\x08.DataRef\"\x00\x12\"\n\x03Get\x12\x08.DataRef\x1a\x0f.StatusWithData\"\x00\x12\x18\n\x03Put\x12\x05.Data\x1a\x08.DataRef\"\x00P\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raylet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WORKERDATA._serialized_start=37
  _WORKERDATA._serialized_end=63
  _VOLPY._serialized_start=66
  _VOLPY._serialized_end=262
# @@protoc_insertion_point(module_scope)
