# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import volpy_pb2 as volpy__pb2

from .volpy_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x04node\x1a\x0bvolpy.proto2[\n\x05Volpy\x12\'\n\x08InitTask\x12\x10.TaskNameAndData\x1a\x07.Status\"\x00\x12)\n\x07RunTask\x12\x0b.IdTaskArgs\x1a\x0f.StatusWithData\"\x00P\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOLPY._serialized_start=35
  _VOLPY._serialized_end=126
# @@protoc_insertion_point(module_scope)
