# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import volpy_pb2 as volpy__pb2


class VolpyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitTask = channel.unary_unary(
                '/node.Volpy/InitTask',
                request_serializer=volpy__pb2.TaskNameAndCode.SerializeToString,
                response_deserializer=volpy__pb2.Status.FromString,
                )
        self.RunTask = channel.unary_unary(
                '/node.Volpy/RunTask',
                request_serializer=volpy__pb2.IdTaskArgs.SerializeToString,
                response_deserializer=volpy__pb2.StatusWithData.FromString,
                )


class VolpyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitTask(self, request, context):
        """Task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VolpyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.InitTask,
                    request_deserializer=volpy__pb2.TaskNameAndCode.FromString,
                    response_serializer=volpy__pb2.Status.SerializeToString,
            ),
            'RunTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTask,
                    request_deserializer=volpy__pb2.IdTaskArgs.FromString,
                    response_serializer=volpy__pb2.StatusWithData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'node.Volpy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Volpy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/node.Volpy/InitTask',
            volpy__pb2.TaskNameAndCode.SerializeToString,
            volpy__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/node.Volpy/RunTask',
            volpy__pb2.IdTaskArgs.SerializeToString,
            volpy__pb2.StatusWithData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
